Update update.yml

diff --git a/.github/workflows/update.yml b/.github/workflows/update.yml
--- a/.github/workflows/update.yml
+++ b/.github/workflows/update.yml
@@ -28,6 +28,12 @@ jobs:
         run: |
           git config --global user.name "github-actions[bot]"
           git config --global user.email "github-actions[bot]@users.noreply.github.com"
-          git add torrent-urls.txt
-          git commit -m "Auto update torrent list" || echo "No changes to commit"
-          git push
+          git status
+          if [ -f torrent-urls.txt ]; then
+            git add torrent-urls.txt
+            git commit -m "Auto update torrent list" || echo "No changes to commit"
+            git push
+          else
+            echo "torrent-urls.txt not found"
+          fi
+
